version: "3"
services:
  app-client:
    build:
      context: ./app
    ports:
      - "3000:3000"
    container_name: app-client
    stdin_open: true
    volumes:
      - ./app:/usr/src/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
